server:
  port: 9000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.23.67.36:3307/kob?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

mybatis-plus:
  global-config:
    banner: false

logging:
  file:
    name: backend/logs/spring.log
  logback:
    rollingpolicy:
      max-file-size: 1MB
      file-name-pattern: backend/logs/spring.%d{yyyy-MM-dd}.%i.log
  level:
    root: info

matching-system:
  addPlayerUrl: http://127.0.0.1:3001/player/add
  removePlayerUrl: http://127.0.0.1:3001/player/remove

botrunning-system:
  addBotUrl: http://127.0.0.1:3002/botrunning/add
